UPDATE "mstSvt" SET "cnName" = '玛修·基列莱特' where id = 800100;
-- mstCv
UPDATE "mstCv" SET "cnName" = '野中蓝&川澄绫子' WHERE "id" = 16;
UPDATE "mstCv" SET "cnName" = '神奈延年&泽城美雪' WHERE "id" = 19;
UPDATE "mstCv" SET "cnName" = '' WHERE "id" = 50;
UPDATE "mstCv" SET "cnName" = '门胁舞以&高野直子' WHERE "id" = 57;
UPDATE "mstCv" SET "cnName" = '加濑康之&堀江由衣' WHERE "id" = 92;
UPDATE "mstCv" SET "cnName" = '田中美海&小松未可子&雨宫天' WHERE "id" = 95;
UPDATE "mstCv" SET "cnName" = '名塚佳织&嘉数由美' WHERE "id" = 103;
UPDATE "mstCv" SET "cnName" = '上田丽奈&小野大辅' WHERE "id" = 108;
UPDATE "mstCv" SET "cnName" = '内田雄马&内田真礼' WHERE "id" = 127;
-- mstIllustrator
UPDATE "mstIllustrator" SET "cnName" = 'YUKISAME&秋田犬' WHERE "id" = 104;
UPDATE "mstIllustrator" SET "cnName" = '秋田犬&Veia' WHERE "id" = 110;
UPDATE "mstIllustrator" SET "cnName" = '武内崇&高桥庆太郎&WADA ARUKO&近卫乙嗣' WHERE "id" = 117;
UPDATE "mstIllustrator" SET "cnName" = '竹&Veia' WHERE "id" = 148;
UPDATE "mstIllustrator" SET "cnName" = '白峰&Kawaguchi Takeshi' WHERE "id" = 200;
UPDATE "mstIllustrator" SET "cnName" = '泷山真哲&山村洋贵' WHERE "id" = 201;
UPDATE "mstIllustrator" SET "cnName" = '武内崇&下越&Azusa&pako&BSUKE&本庄雷太&MORII SHIZUKI&BSUKE' WHERE "id" = 225;
-- mstItem
UPDATE "mstItem" SET "cnName" = 'QP' WHERE "id" = 1;
UPDATE "mstItem" SET "cnName" = '圣晶石' WHERE "id" = 2;
UPDATE "mstItem" SET "cnName" = '魔力棱镜' WHERE "id" = 3;
UPDATE "mstItem" SET "cnName" = '友情点数' WHERE "id" = 4;
UPDATE "mstItem" SET "cnName" = '任务完成报酬 QP' WHERE "id" = 5;
UPDATE "mstItem" SET "cnName" = '圣晶石' WHERE "id" = 6;
UPDATE "mstItem" SET "cnName" = '圣晶片' WHERE "id" = 11;
UPDATE "mstItem" SET "cnName" = '圣晶片' WHERE "id" = 16;
UPDATE "mstItem" SET "cnName" = '无记名灵基' WHERE "id" = 17;
UPDATE "mstItem" SET "cnName" = '稀有魔力棱镜' WHERE "id" = 18;
UPDATE "mstItem" SET "cnName" = '？？？' WHERE "id" = 99;
UPDATE "mstItem" SET "cnName" = '黄金果实' WHERE "id" = 100;
UPDATE "mstItem" SET "cnName" = '白银果实' WHERE "id" = 101;
UPDATE "mstItem" SET "cnName" = '赤铜果实' WHERE "id" = 102;
UPDATE "mstItem" SET "cnName" = '迦勒底梦火' WHERE "id" = 1000;
UPDATE "mstItem" SET "cnName" = '兽之足迹' WHERE "id" = 2000;
UPDATE "mstItem" SET "cnName" = '呼符' WHERE "id" = 4001;
UPDATE "mstItem" SET "cnName" = '迅纹章开启器' WHERE "id" = 5000;
UPDATE "mstItem" SET "cnName" = '技纹章开启器' WHERE "id" = 5001;
UPDATE "mstItem" SET "cnName" = '力纹章开启器' WHERE "id" = 5002;
UPDATE "mstItem" SET "cnName" = '纹章移除器' WHERE "id" = 5003;
UPDATE "mstItem" SET "cnName" = '圣杯' WHERE "id" = 7999;